### ISSUE TITLE
Stream not initialising

### ISSUE THREAD

**Issue by iam-kanavsharma** [arerlend/azure-schemaregistry-spark#3]
Hello @arerlend 

<img width="1094" alt="no_execution_eventhubs_scehmaregistry" src="https://user-images.githubusercontent.com/78341015/109392126-6a1bb280-7940-11eb-8621-87da5346c175.png">

I am trying to access and diaplsy the event hub on console from the databricks workspace. The data is serialised in avro format and i am using the schema registry to deserialise it.

But the command seems to run indefinitely with no output. Looks like stream is not even initialised. I have attached the image depicting the same. It looks the same for about 1 hour.

Just to check the code, I also tried converting to string, the data was not as expected (of course since its stored as avro) but the stream was initialised at least.

Can you help out ? Thanks.

**Comment by iam-kanavsharma** [comment]
Hi, Any update Arthur @arerlend

**Comment by arerlend** [comment]
Hi @iam-kanavsharma in the future you can check azure-event-hubs-spark here, PR is not completed yet - https://github.com/Azure/azure-event-hubs-spark/pull/573.

I can provide a private build for now if you email me.

**Comment by mpfis** [comment]
I am finding the same issue when trying to implement this on a Databricks cluster. It does not seem to be able to connect / pull the schema from the schema registry.

**Comment by arerlend** [comment]
@mpfis I would check the PR on the azure-event-hubs-spark repo since I finished my time at MSFT.

I did test the package before I left and had no issues.
